Simulador_Cajero/Cajero_Pichincha/urls.py
from django.urls import path
from . import views

app_name = 'Cajero_Pichincha'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('display_bank_services/', views.display_bank_services, name='display_bank_services'),
    path('register/', views.register, name='register'),
    path('deposit/', views.deposit, name='deposit'),
    path('withdraw/', views.withdraw, name='withdraw'),
]

Simulador_Cajero/Simulador_Cajero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Cajero_Pichincha.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Simulador_Cajero/Cajero_Pichincha/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MinLengthValidator, MaxLengthValidator, RegexValidator
import random

class User(AbstractUser):
    email = models.EmailField(
        unique=True,
        verbose_name='Correo electrónico'
    )
    phone_number = models.CharField(
        max_length=10,
        validators=[RegexValidator(r'^\d{10}$', 'Ingrese 10 dígitos numéricos.')],
        blank=True,
        null=True,
        verbose_name='Teléfono'
    )
    identification = models.CharField(
        max_length=10,
        unique=True,
        validators=[RegexValidator(r'^\d{10}$', 'Ingrese 10 dígitos numéricos.')],
        blank=True,
        null=True,
        verbose_name='Cédula'
    )
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'identification']

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
        
    def __str__(self):
        return self.username

class Account(models.Model):
    ACCOUNT_TYPE = [
        ('corriente', 'Corriente'),
        ('ahorro', 'Ahorro')
    ]

    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='accounts',
        verbose_name='Usuario'
    )
    account_number = models.CharField(
        max_length=10,
        unique=True,
        editable=False,
        verbose_name='Número de cuenta'
    )
    account_type = models.CharField(
        max_length=10, 
        choices=ACCOUNT_TYPE,
        verbose_name='Tipo de cuenta'
    )
    funds = models.DecimalField(
        max_digits=12, 
        decimal_places=2, 
        default=0.00,
        verbose_name='Saldo'
    )

    def deposit(self, amount):
        self.funds += amount
        self.save()

    def __str__(self):
        return f"{self.user.username} - {self.account_number}"

    def save(self, *args, **kwargs):
        if not self.account_number:
            while True:
                number = ''.join([str(random.randint(0, 9)) for _ in range(10)])
                if not Account.objects.filter(account_number=number).exists():
                    self.account_number = number
                    break
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username} - {self.account_number} - {self.account_type}"

    class Meta:
        verbose_name = 'Cuenta'
        verbose_name_plural = 'Cuentas'

class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('DEPOSITO', 'Depósito'),
        ('RETIRO', 'Retiro'),
        ('TRANSFERENCIA', 'Transferencia'),
        ('PAGO SERVICIOS BASICOS', 'Pago de servicios básicos')
    ]
    
    account = models.ForeignKey(
        Account, 
        on_delete=models.CASCADE, 
        related_name='transactions',
        verbose_name='Cuenta'
    )
    transaction_type = models.CharField(
        max_length=50, 
        choices=TRANSACTION_TYPES,
        verbose_name='Tipo de transacción'
    )
    amount = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(0.01)],
        verbose_name='Monto'
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha y hora'
    )
    description = models.CharField(
        max_length=255, 
        blank=True, 
        null=True,
        verbose_name='Descripción'
    )
    destination = models.CharField(
        max_length=100, 
        blank=True, 
        null=True)

    def __str__(self):
        return f"{self.transaction_type} - {self.amount} on {self.timestamp}"

    class Meta:
        verbose_name = 'Transacción'
        verbose_name_plural = 'Transacciones'

class Service(models.Model):
    SERVICE_TYPES = [
        ('AGUA', 'Factura de agua'),
        ('ELECTRICIDAD', 'Factura de Luz'),
    ]
    
    account = models.ForeignKey(
        Account, 
        on_delete=models.CASCADE,
        verbose_name='Cuenta'
    )
    service_type = models.CharField(
        max_length=20, 
        choices=SERVICE_TYPES,
        verbose_name='Tipo de servicio'
    )
    bill_number = models.CharField(
        max_length=10,
        verbose_name='Número de factura'
    )
    amount = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        verbose_name='Monto'
    )
    payment_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha de pago'
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name='Pagado'
    )

    def __str__(self):
        return f"{self.service_type} payment - {self.bill_number}"

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

Simulador_Cajero/Cajero_Pichincha/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import User, Account

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'identification', 'phone_number', 'password1', 'password2']
        error_messages = {
            'username': {
                'unique': 'Este nombre de usuario ya está en uso.',
                'required': 'El nombre de usuario es obligatorio.'
            },
            'email': {
                'unique': 'Este correo ya está registrado.',
                'invalid': 'Por favor ingrese un correo válido.',
                'required': 'El correo electrónico es obligatorio.'
            },
            'identification': {
                'unique': 'Esta cédula ya está registrada.',
                'invalid': 'Ingrese una cédula válida de 10 dígitos.',
                'required': 'La cédula es obligatoria.'
            },
            'phone_number': {
                'invalid': 'Ingrese un número de teléfono válido de 10 dígitos.',
                'required': 'El número de teléfono es obligatorio.'
            },
            'password1': {
                'invalid': 'Ingrese una contraseña válida.',
                'required': 'La contraseña es obligatoria.',
                'min_length': 'La contraseña debe tener al menos 8 caracteres.',
            },
            'password2': {
                'invalid': 'Ingrese una contraseña válida.',
                'required': 'Debe confirmar su contraseña.',
                'password_mismatch': 'Las contraseñas no coinciden.'
            }
        }
                

class AccountCreationForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['account_type']
        labels = {
            'account_type': 'Tipo de cuenta',
        }

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de usuario'}),
        error_messages={
            'required': 'Por favor ingrese su nombre de usuario.',
            'invalid': 'Usuario inválido.'
        }
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}),
        error_messages={
            'required': 'Por favor ingrese su contraseña.',
            'invalid': 'Contraseña inválida.'
        }
    )

    error_messages = {
        'invalid_login': 'Usuario o contraseña incorrectos. Por favor intente nuevamente.',
        'inactive': 'Esta cuenta está inactiva.',
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Nombre de Usuario'
        self.fields['password'].label = 'Contraseña'

class DepositForm(forms.Form):
    amount = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        min_value=0.01,
        label="Monto a depositar",
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa el monto'}),
    )

class WithdrawForm(forms.Form):
    amount = forms.DecimalField(
        label="Monto a retirar",
        max_digits=10,
        decimal_places=2,
        min_value=0.01
    )

Simulador_Cajero/Cajero_Pichincha/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CustomUserCreationForm, AccountCreationForm, LoginForm, DepositForm, WithdrawForm
import logging
from .models import User, Account, Transaction

def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('Cajero_Pichincha:display_bank_services')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

@login_required
def display_bank_services(request):
    user = User.objects.get(username=request.user)
    account = Account.objects.get(user=request.user)
    transactions = Transaction.objects.filter(account=account).order_by('-timestamp')[:3]
    return render(request, 'display_bank_services.html', {
        'user': user,
        'account': account,
        'transactions': transactions
    })

    logger = logging.getLogger(__name__)
    

def logout_view(request):
    print("Iniciando proceso de logout")  # Debug
    print(f"Usuario antes de logout: {request.user}")  # Debug
    
    try:
        logout(request)
        print(f"Usuario después de logout: {request.user}")  # Debug
        messages.success(request, 'Has cerrado sesión exitosamente')
        print("Redirigiendo a index")  # Debug
        return redirect('Cajero_Pichincha:index')
    except Exception as e:
        print(f"Error en logout: {str(e)}")  # Debug
        return redirect('Cajero_Pichincha:index')
    
def register(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        account_form = AccountCreationForm(request.POST)
        if user_form.is_valid() and account_form.is_valid():
            user = user_form.save()
            account = account_form.save(commit=False)
            account.user = user
            account.save()
            return redirect('Cajero_Pichincha:login')
    else:
        user_form = CustomUserCreationForm()
        account_form = AccountCreationForm()
    return render(request, 'register.html', {
        'user_form': user_form,
        'account_form': account_form
    })

@login_required
def deposit(request):
    account = Account.objects.get(user=request.user)
    if request.method == 'POST':
        form = DepositForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            account.deposit(amount)
            Transaction.objects.create(
                account=account,
                transaction_type='DEPOSIT',
                amount=amount,
            )
            messages.success(request, f"Depósito de ${amount} realizado con éxito.")
            return redirect('Cajero_Pichincha:display_bank_services')
    else:
        form = DepositForm()

    return render(request, 'deposit.html', {'form': form, 'account': account})

@login_required
def withdraw(request):
    account = Account.objects.filter(user=request.user).first()
    
    if not account:
        messages.error(request, "No tienes una cuenta asociada.")
        return redirect('Cajero_Pichincha:display_bank_services')

    if request.method == "POST":
        form = WithdrawForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']

            if amount > account.funds:
                messages.error(request, "Fondos insuficientes.")
            else:
                # Restar el dinero de la cuenta
                account.funds -= amount
                account.save()

                # Registrar la transacción
                Transaction.objects.create(
                    account=account,
                    transaction_type='withdraw',
                    amount=amount
                )

                messages.success(request, f"Has retirado ${amount} exitosamente.")
                return redirect('Cajero_Pichincha:display_bank_services')
    else:
        form = WithdrawForm()

    return render(request, 'withdraw.html', {'form': form, 'account': account})

Simulador_Cajero/Cajero_Pichincha/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Banco Pichincha{% endblock %}</title>
        <link rel="icon" type="image/png" href="{% static 'logo.png' %}">
        <link href="{% static 'pichincha_theme.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
        <link href="{% static 'styles.css' %}" rel="stylesheet">
        <link href="{% static 'sidebar.css' %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'js/sidebar_toggle.js' %}" defer></script>
    </head>
    <body>
        <nav class="navbar bg-primary navbar-custom w-100">
                <a class="navbar-brand" href="{% if user.is_authenticated %}{% url 'Cajero_Pichincha:display_bank_services' %}{% else %}{% url 'Cajero_Pichincha:index' %}{% endif %}">
                    <img src="{% static 'banner_pichincha.png' %}" alt="Pichincha Banner" title="Pichincha Banner" class="banner-img">
                </a>
                <div class="d-flex justify-content-end {% block navbar_class %}{% endblock navbar_class %}">
                    <ul class="nav">
                        {% if user.is_authenticated %}
                            {% if request.path != '/display_bank_services/' %}
                                <li class="nav-item">
                                    <a class="nav-link nav-link-custom" style="font-size: 22px" href="{% url 'Cajero_Pichincha:display_bank_services' %}">Servicios Bancarios</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link nav-link-custom" style="font-size: 22px" href="{% url 'Cajero_Pichincha:logout' %}">Cerrar Sesión</a>
                            </li>
                        {% else %}
                            {% if request.path == '/login/' or request.path == '/register/' %}
                                <li class="nav-item">
                                    <a class="nav-link nav-link-custom" style="font-size: 22px" href="{% url 'Cajero_Pichincha:index' %}">Inicio</a>
                                </li>
                            {% endif %}
                            {% if request.path == '/' %}
                                <li class="nav-item">
                                    <a class="nav-link nav-link-custom" style="font-size: 22px" href="{% url 'Cajero_Pichincha:login' %}">Iniciar Sesión</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link nav-link-custom" style="font-size: 22px" href="{% url 'Cajero_Pichincha:register' %}">Registrarse</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            {% block content %}{% endblock %}
        {% block extra_scripts %}{% endblock %}
    </body>
</html>

Simulador_Cajero/Cajero_Pichincha/templates/deposit.html
{% extends "base.html" %}
{% block title %}Depósito{% endblock title %}

{% block content %}
<div class="container form-container">
    <h2>Realizar Depósito</h2>
    <p>Cuenta: {{ account.account_number }}</p>
    <p>Saldo actual: ${{ account.funds }}</p>
    <form method="post" action="{% url 'Cajero_Pichincha:deposit' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Depositar</button>
    </form>
</div>
{% endblock content %}

Simulador_Cajero/Cajero_Pichincha/templates/display_bank_services.html
{% extends "base.html" %}
{% block title %}Servicios Bancarios{% endblock title %}

{% block content %}
<br>
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12">
            <button class="btn btn-primary mb-3" id="menu-toggle" style="margin-left: 15px;">
                <i class="fas fa-bars"></i> Menú
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <div class="d-flex" id="wrapper">
                <!-- Sidebar -->
                <div class="border-end bg-white" id="sidebar-wrapper">
                    <div class="sidebar-heading border-bottom bg-secondary">Servicios Bancarios</div>
                    <div class="list-group list-group-flush">
                        <a href="#" class="list-group-item list-group-item-action p-3">Consulta de Saldo</a>
                        <a href="{% url 'Cajero_Pichincha:withdraw' %}" class="list-group-item list-group-item-action p-3">Retiro</a>
                        <a href="{% url 'Cajero_Pichincha:deposit' %}" class="list-group-item list-group-item-action p-3">Depósito</a>
                        <a href="#" class="list-group-item list-group-item-action p-3">Transferencias</a>
                        <a href="#" class="list-group-item list-group-item-action p-3">Pago de servicios básicos</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9 mt-n2">
            <h1 class="pt-0 mb-3">Bienvenido/a: {{user.username}}</h1>
            {% if account %}
                <div class="card mt-n2" style="width: 40rem;">
                    <div class="card-header bg-primary">
                        <h3 class="font-size: 20px">Mi cuenta</h3>
                    </div>
                    <ul class="list-group list-group-flush">
                        <br>
                        <li class="list-group-item">Numero de cuenta: {{account.account_number}}</li>
                        <br>
                        <li class="list-group-item">Saldo disponible: {{account.funds}}</li>
                        <br>
                        <li class="list-group-item">Tipo de cuenta: {{account.get_account_type_display}}</li>
                    </ul>
                </div>
                <br>

                <div class="card mt-n2" style="width: 40rem;">
                    <div class="card-header bg-primary">
                        <h3 class="font-size: 20px">Últimos movimientos</h3>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for transaction in transactions %}
                        <li class="list-group-item">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <strong>{{ transaction.get_transaction_type_display }}</strong>
                                    {% if transaction.destination %}
                                        → {{ transaction.destination }}
                                    {% endif %}
                                </div>
                                <div>
                                    ${{ transaction.amount }}
                                </div>
                            </div>
                            <small class="text-muted">{{ transaction.timestamp|date:"d/m/Y H:i" }}</small>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

            {% endif %}
            
        </div>
    </div>
</div>
{% endblock %}

Simulador_Cajero/Cajero_Pichincha/templates/display_transfer.html
{% extends "base.html" %}
{% block title %}Transferencia{% endblock title %}
{% block navbar_class %}hide-elements{% endblock navbar_class %}

{% block content %}
<div class="container form-container">
    <br>
    <h2>Transferencia</h2>
    <br>
    <form method="post" action="{% url 'Cajero_Pichincha:display_transfer' %}">
        {% csrf_token %}
        <div class="login-item">
            <div class="form-group">
                <h2 class="mb-1" style="font-size:20px">Cuenta de origen: {{ account.account_number }}</h2>
                <small class="text-muted" style="font-size=10px">Titular: {{ account.user.username }}</small>
            </div>
            <div class="form-group">
                <label for="{{ transfer_form.account_number.id_for_label }}">Cuenta de destino</label>
                <input type="text" 
                       name="account_number" 
                       id="id_account_number" 
                       class="form-control" 
                       value="{{ request.GET.account_number }}"
                       placeholder="Ingrese el número de cuenta">
                {% if transfer_form.account_number.errors %}
                    <div class="error-message alert alert-danger">
                        {% for error in transfer_form.account_number.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
                <div id="destinationAccountHolder">
                    {% if destination_account %}
                        <small class="text-muted">Titular: {{ destination_account.user.username }}</small>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="{{ transfer_form.amount.id_for_label }}">Monto</label>
                {{ transfer_form.amount }}
                {% if transfer_form.amount.errors %}
                    <div class="error-message alert alert-danger">
                        {% for error in transfer_form.amount.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <br>
            <button type="submit" class="btn btn-primary w-100">Transferir</button>
        </div>
    </form>
</div>

<script>
document.getElementById('id_account_number').addEventListener('change', function() {
    if (this.value) {
        window.location.href = `?account_number=${this.value}`;
    }
});
</script>
{% endblock content %}

Simulador_Cajero/Cajero_Pichincha/templates/index.html
{% extends "base.html" %}
{% block title %}Banco Pichincha{% endblock title %}
{% block content %}
    <div class="container basic-service">
        <img src="static/display_bankinfo.jpg" alt="bankinfo">
    </div>
{% endblock content %}

Simulador_Cajero/Cajero_Pichincha/templates/login.html
{% extends "base.html" %}
{% block title %}Página de Inicio de Sesión{% endblock title %}
{% block navbar_class %}hide-elements{% endblock navbar_class %}

{% block content %}
    <div class="container form-container">
        <br>
        <h2>Iniciar Sesión</h2>
        <br>
        <form method="post" action="{% url 'Cajero_Pichincha:login' %}">
            {% csrf_token %}
            <div class="login-item">
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Nombre de Usuario</label>
                    {{ form.username }}
                    {% if form.username.errors %}
                    <div class="error-message">
                        {% for error in form.username.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <small class="form-text text-muted">Recuerda que es tu responsabilidad mantener tu información de ingreso a salvo</small>
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Contraseña</label>
                    {{ form.password }}
                    {% if form.password.errors %}
                    <div class="error-message">
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
                {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
                <br>
                <button type="submit" class="btn btn-primary w-100">Ingresar</button>
            </div>
        </form>
    </div>
{% endblock content %}

Simulador_Cajero/Cajero_Pichincha/templates/register.html
{% extends "base.html" %}
{% block title %}Página de Registro{% endblock title %}
{% block navbar_class %}hide-elements{% endblock navbar_class %}

{% block content %}
<div class="container form-container">
    <br>
    <h2>Registro de Usuario</h2>
    <br>
    <form method="post" action="{% url 'Cajero_Pichincha:register' %}">
        {% csrf_token %}
        <div class="login-item">
            <div class="form-group">
                <label for="{{ user_form.username.id_for_label }}">Nombre de Usuario</label>
                {{ user_form.username }}
                <small class="form-text text-muted">Nombre que usarás para iniciar sesión</small>
            </div>
            <div class="form-group">
                <label for="{{ user_form.email.id_for_label }}">Correo Electrónico</label>
                {{ user_form.email }}
            </div>
            <div class="form-group">
                <label for="{{ user_form.identification.id_for_label }}">Cédula</label>
                {{ user_form.identification }}
            </div>
            <div class="form-group">
                <label for="{{ user_form.phone_number.id_for_label }}">Teléfono</label>
                {{ user_form.phone_number }}
            </div>
            <div class="form-group">
                <label for="{{ user_form.password1.id_for_label }}">Contraseña</label>
                {{ user_form.password1 }}
            </div>
            <div class="form-group">
                <label for="{{ user_form.password2.id_for_label }}">Confirmar Contraseña</label>
                {{ user_form.password2 }}
            </div>
            <div class="form-group">
                <label for="{{ account_form.account_type.id_for_label }}">Tipo de Cuenta</label>
                {{ account_form.account_type }}
            </div>
            {% if user_form.errors or account_form.errors %}
            <div class="form-group">
                <label for="{{ user_form.username.id_for_label }}">Nombre de Usuario</label>
                {{ user_form.username }}
                {% if user_form.username.errors %}
                    <br>
                    <div class="error-message alert alert-danger">
                        {% for error in user_form.username.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
</div>
{% endblock content %}